package: mtq

platform:
  - linux-64
  # - osx-64
  # - win-64

engine:
 - python=2.7

test: 
  - python setup.py develop
  - python -m unittest discover
script:
  - conda build conda.recipe

build_targets: [conda]
