language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "pip install . --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: 
	- python -m unittest discover -v

after_success:
  - pip install coveralls
  - coverage run --source=mtq mtq/tests/runtests.py
  - coveralls

